#+TITLE: README
#+AUTHOR: Christian E. Hopps
#+EMAIL: chopps@gmail.com
#+STARTUP: indent

* Go IS-IS Routing Protocol
This is a partial implementation of the IS-IS routing protocol (ISO 10589:2002)
written in Go. Runs on Linux, OS X, *BSD.

 Yes, this is what I occupy my time with for fun on PTO. :)

** Basic Structure
Is-IS is broken up into 3 processes by design, the Hello, Update and Decision
processes. We have moved the update process to a separate sub-package to align
with this design.

*** Go Routines
- One per circuit to read frames (pktflow.go:readPackets)
- One per circuit to write frames (pktflow.go:writePackets)
- One per LAN link (level) or per P2P link for receiving and sending hello frames
- One per LAN link (level) or per P2P link for processing SRM/SSN flags (flooding)
- One per level for Update Process (LSP DB) which also handles CSNP using a cache.

*** No Locks
The code has no locks. It fully utilizes go's channels to communicate rather
than share memory.

*** Circuits and Links
The code calls an interface a "Circuit". A "Link" then is level specific state
for a Circuit. In particular adjacencies are associated with Links. In the case
of a LAN Circuit there will be one Link per level. In the case of a
point-to-point Circuit there will be only a single Link.

** External Dependencies

- Adaptive Radix Trie ("github.com/plar/go-adaptive-radix-tree")
- Gorilla Mux for serving up state ("github.com/gorilla/mux")

** Implementation notes
- Modern only; no legacy {narrow metrics, 2-way p2p, clns/clnp routing}.
- Supported RFCs of note
  - RFC5301 Dyanmic Hostname
  - RFC5305 Extended Reachability
  - RFC5308 IPv6 supported
** TODO Missing Items
*** Immediate need
- Implement Decision Process (SPF)
- Implement P2P interfaces (RFC5303 3-way, RFC5309 p2pOverLAN)
- RFC 6232 - purge origination (easy)
- RFC 5306 - Restart signaling (neighbor support)

*** Want
- RFC 5310 - Generic Cryptographic Authentication
- RFC 5304 - Cryptographic Authentication

*** Maybe never.
- RFC 5302 - Domain wide distribution, no route leaking.
- RFC 5306 - Restart signaling (local support)
- RFC 5307 - GMPLS
- RFC 5311 - Simplifiied Extension of LSP space?
